"""Add display_name to users

Revision ID: 9d6fd8ddf4ee
Revises: 6fa10b9f0146
Create Date: 2026-03-09 06:19:44.112145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6fd8ddf4ee'
down_revision = '6fa10b9f0146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
